main: me.desmondcchi.powertools.Main
name: Powertools
author: desmondcchi
version: 0.0.1
api-version: 1.19
commands:
   powertool:
      usage: /powertool <COMMAND>
      aliases: pt
      description: Set command to powertool. (Use /powertool to reset)